{% set name = "parfive" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cd6cb419242130730cf41d4cf6f284ebf50f1a71ce6c9508e0467ec98f17dc8e

build:
  number: 1
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - tqdm
    - aiohttp
    - aioftp
    - aiofiles

test:
  imports:
    - parfive
  requires:
    - pytest
    - pytest-localserver
    - pytest-asyncio
    - pytest-socket
    - python {{ python_min }}
  commands:
    - pytest --pyargs parfive -m "not allow_hosts" -k "not test_session_config_defaults"

about:
  home: https://parfive.readthedocs.io/en/latest/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A parallel file downloader using asyncio.
  doc_url: https://parfive.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - Cadair
    - nabobalis
    - wtbarnes
