travis:
  secure:
    BINSTAR_TOKEN: OIORvlH/Gh8Po2gS6SyNdUKrX3X3+B5dFVDLE5ARfbSPDN4T8cJWl/gTQnzHYYfuz1sNMzz/ZM5390qq/rJCLWpY+xtGGwrLwNp/eWsR8MNC+OZMyFk5Fghzj4ZVhmiLHmTg5mzLlgW1CZjEZl2P7uqVnnIn0kTiezzmX9Zya/bXaEuxSar7QXbT9EFUAMKthwOEIe4aoyHO+kkRonjYVqzr0MYWjGR4c6CUuBXfDjJfOK0QwG8TdT7Muy4EoXGAg3KzKgMo3JnAs9t91OQHZ3WLbDUP2Wq52gLgsw/cNzKaq70kvrKdpg2UG3z0hgHwy2+Rh7DLmwV6dz61fTbmlCaZKN9pnrkjzUI+sFFJEf0pB+byzlC1MozUwPrbmx5KBwuXPq7Pgi96vySjEB4dU9AT59+pXHecsu6nSv78qMLZvasVu7jbQKT7ZSSO1Qk/HNQ71JigBLHWhO4VBNCVXi5t/L1LTN8mYT91Vct087D7vquW/RPcjWKVd6broj5puJe4z7ibFwIi+Mtt1NkpMBGgCA3xpv5i78umbYsBGD0Pc3g3R/xP+61XlWgCjTSa44He6LSNvWEZhZVON6ja5z7vB9snDl8WWhGzjGK9g0xUVokC9VwbCSanMrpBF8t+M3qUdhtsiFHEKQFfcp2THIjGCdTEbxxf6a1RXCmIXYw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
